name: smallantimagmas
version: "0.3.0"
license: "GPL-3.0-or-later"
date: 2025-01-04
description: |
    A library of antiassociative magmas of small order

authors:
    - name: Kamil Zabielski

maintainers:
    - name: Kamil Zabielski

GAP: "4.12"

needed-pkgs:
    - name: "GAPDoc"
      version: "1.5"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://limakzi.github.io/smallantimagmas
readme: README.md
packageinfo: https://limakzi.github.io/smallantimagmas/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/limakzi/smallantimagmas/releases/download/v0.3.0/smallantimagmas-v0.3.0.tar.gz

abstract: |
    The <span class="pkgname">smallantimagmas</span> package,    classifies all finite, antassociative magmas.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    smallantimagmas, antiassociative.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Zab25</span>]   <b class='BibAuthor'>Zabielski, K.</b>,
     <i class='BibTitle'>smallantimagmas, A library of antiassociative magmas of small order,
             Version 0.3.0</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://limakzi.github.io/smallantimagmas">https://limakzi.github.io/smallantimagmas</a></span>.
    </p>
    

bibtex: |
    @misc{ smallantimagmas,
      author =           {Zabielski, K.},
      title =            {{smallantimagmas}, A library of antiassociative magmas
                          of small order, {V}ersion 0.3.0},
      month =            {Jan},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href      {https://limakzi.github.io/smallantimagmas}
                          {\texttt{https://limakzi.github.io/}\discretionary
                          {}{}{}\texttt{smallantimagmas}}},
      keywords =         {smallantimagmas; antiassociative},
      printedkey =       {Zab25}
    }

