gap> START_TEST("test_properties_magma_rank.tst");

## MinimalGeneratingSet(M) generates M
gap> ForAll(AllSmallAntimagmas([2 .. 4]), M -> Submagma(M, MinimalGeneratingSet(M)) = M);
true

## Rank(M) = Size(MinimalGeneratingSet(M))
gap> ForAll(AllSmallAntimagmas([2 .. 4]), M -> Rank(M) = Size(MinimalGeneratingSet(M)));
true

## no smaller set generates M
gap> ForAll(AllSmallAntimagmas([2 .. 4]), M -> ForAll(Combinations(Elements(M), Rank(M) - 1),
>        c -> IsEmpty(c) or Size(Submagma(M, c)) < Size(M)));
true

## every antimagma of order 2 or 3 is generated by one element
gap> ForAll(AllSmallAntimagmas([2 .. 3], "up-to-isomorphism"), M -> Rank(M) = 1);
true

## all but 183 isomorphism classes of order 4 are generated by one element
gap> Collected(List(AllSmallAntimagmas(4, "up-to-isomorphism"), Rank));
[ [ 1, 17597 ], [ 2, 183 ] ]

## Rank(M) = Rank(TransposedMagma(M))
gap> ForAll(AllSmallAntimagmas([2 .. 4]), M -> Rank(M) = Rank(TransposedMagma(M)));
true

## an element that is not a product belongs to every generating set
gap> M := SmallAntimagma(4, 1);;
gap> Display(MultiplicationTable(M));
[ [  2,  1,  1,  1 ],
  [  2,  1,  1,  1 ],
  [  2,  1,  1,  1 ],
  [  2,  1,  1,  1 ] ]
gap> MinimalGeneratingSet(M);
[ m3, m4 ]
gap> Rank(M);
2

## a magma generated by one element
gap> M := MagmaByMultiplicationTable([[2, 3, 1], [3, 1, 2], [1, 2, 3]]);;
gap> MinimalGeneratingSet(M);
[ m1 ]
gap> Rank(M);
1

## Rank of a group is left to the GAP library
#@if IsPackageMarkedForLoading( "smallgrp", "" )
gap> Size(MinimalGeneratingSet(CyclicGroup(6)));
1
gap> Rank(CyclicGroup(4));
1
#@fi

gap> STOP_TEST("test_properties_magma_rank.tst");
