gap> START_TEST("test_properties_magma_cyclic.tst");

# Test 1: Raw test with multiplication table
# This magma is NOT cyclic - it's generated by S = {3, 4} but no single element generates it
gap> M := MagmaByMultiplicationTable([[2, 1, 1, 1], [2, 1, 1, 1], [2, 1, 1, 1], [2, 1, 1, 1]]);
<magma with 4 generators>
gap> IsCyclic(M);
false

# Test 2: Test with SmallAntimagma(4,1)
gap> M := SmallAntimagma(4, 1);
<magma with 4 generators>
gap> IsCyclic(M);
false

gap> STOP_TEST("test_properties_magma_cyclic.tst");
