gap> START_TEST("test_generating_set.tst");

# Test that all antimagmas of order 2 and 3 are generated by one element
gap> ForAll(AllSmallAntimagmas(2), M -> Length(MinimalGeneratingSet(M)) = 1);
true

gap> ForAll(AllSmallAntimagmas(3), M -> Length(MinimalGeneratingSet(M)) = 1);
true

# Test that antimagma [4,1] is generated by two elements
gap> Length(MinimalGeneratingSet(SmallAntimagma(4, 1))) = 2;
true

# Test all antimagmas of size 2..4
gap> ForAll(AllSmallAntimagmas([2 .. 4]), M -> Size(Submagma(M, MinimalGeneratingSet(M))) = Size(M));
true

gap> STOP_TEST("test_generating_set.tst");
