---
name: Feature Request
description: Suggest a new feature or enhancement for this project
title: "[Feature Request]: "
projects: ["limakzi/smallantimagmas"]
labels: ["feature", "triage"]
assignees:
  - limakzi

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest a feature for our project. Please fill out the following sections to help us understand your request better.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low
        - Medium
        - High

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Describe the potential impact of this feature on the project or users.

  - type: textarea
    id: resources
    attributes:
      label: Resources
      description: Are there any resources, documentation, or examples that might be helpful for implementing this feature?
