gap> START_TEST("property_rank.tst");

## Rank(M) = Size(MinimalGeneratingSet(M)), the set generates M, and no smaller set does.
gap> ForAll(AllSmallAntimagmas([2 .. 4]), M -> Submagma(M, MinimalGeneratingSet(M)) = M);
true
gap> ForAll(AllSmallAntimagmas([2 .. 4]), M -> Rank(M) = Size(MinimalGeneratingSet(M)));
true
gap> ForAll(AllSmallAntimagmas([2 .. 4]), M -> ForAll(Combinations(Elements(M), Rank(M) - 1),
>        c -> IsEmpty(c) or Size(Submagma(M, c)) < Size(M)));
true

## Rank(M) = 1 iff some element generates M.
gap> ForAll(AllSmallAntimagmas([2 .. 4]), M -> (Rank(M) = 1) = ForAny(M, m -> Submagma(M, [m]) = M));
true

## A left or right cyclic antimagma is generated by one element.
gap> ForAll(Filtered(AllSmallAntimagmas([2 .. 4]), M -> IsLeftCyclic(M) or IsRightCyclic(M)), M -> Rank(M) = 1);
true

## Every antimagma of order 2 or 3 is generated by one element.
gap> ForAll(AllSmallAntimagmas([2 .. 3], "up-to-isomorphism"), M -> Rank(M) = 1);
true

## Antimagmas of order 4 are generated by one or two elements.
gap> ForAll(AllSmallAntimagmas(4), M -> Rank(M) <= 2);
true

## Rank 2 is not forced by missing products.
gap> ForAny(AllSmallAntimagmas(4), M -> Rank(M) = 2 and ProductSetSize(M) = 4);
true

## Elements outside the product set M * M lie in every generating set.
gap> ForAll(AllSmallAntimagmas(4), M -> Rank(M) >= Size(M) - ProductSetSize(M));
true
gap> ForAll(AllSmallAntimagmas(4), M -> IsSubset(MinimalGeneratingSet(M),
>        Difference(Elements(M), Set(EnumeratorOfTuples(M, 2), t -> t[1] * t[2]))));
true

## Rank is invariant under isomorphism and antiisomorphism.
gap> ForAll(AllSmallAntimagmas(4, "up-to-isomorphism"), function(M)
>        local t, p;
>        t := MultiplicationTable(M);
>        p := Random(SymmetricGroup(4));
>        return Rank(M) = Rank(MagmaByMultiplicationTable(
>            List([1 .. 4], i -> List([1 .. 4], j -> t[i / p][j / p] ^ p))));
>    end);
true
gap> ForAll(AllSmallAntimagmas([2 .. 4]), M -> Rank(M) = Rank(TransposedMagma(M)));
true

gap> STOP_TEST("property_rank.tst");
