gap> START_TEST("property_rank.tst");

## Rank of a group is left to the GAP library.
#@if IsPackageMarkedForLoading( "smallgrp", "" )
gap> Rank(CyclicGroup(4));
1
#@fi

## The antimagma of order 2 is generated by either element.
gap> M := MagmaByMultiplicationTable([[2, 1], [2, 1]]);;
gap> Rank(M);
1
gap> MinimalGeneratingSet(M);
[ m1 ]

## A one-generated antimagma of order 4: m4 generates, since m4, m4 * m4 = m1, m1 * m1 = m2, m4 * m1 = m3 exhaust M.
gap> M := MagmaByMultiplicationTable([[2, 1, 1, 1], [2, 1, 1, 1], [2, 1, 1, 1], [3, 1, 1, 1]]);;
gap> Rank(M);
1
gap> MinimalGeneratingSet(M);
[ m4 ]

## A two-generated antimagma of order 4: m3 and m4 are not products, so both belong to every generating set.
gap> M := MagmaByMultiplicationTable([[2, 1, 1, 1], [2, 1, 1, 1], [2, 1, 1, 1], [2, 1, 1, 1]]);;
gap> Rank(M);
2
gap> MinimalGeneratingSet(M);
[ m3, m4 ]

## A two-generated antimagma of order 4 in which every element is a product.
gap> M := MagmaByMultiplicationTable([[2, 1, 1, 1], [2, 1, 1, 1], [3, 1, 1, 1], [4, 1, 1, 1]]);;
gap> Rank(M);
2
gap> MinimalGeneratingSet(M);
[ m3, m4 ]

## A left zero magma is generated only by all of its elements.
gap> M := MagmaByMultiplicationTable([[1, 1, 1], [2, 2, 2], [3, 3, 3]]);;
gap> Rank(M);
3
gap> MinimalGeneratingSet(M);
[ m1, m2, m3 ]

## The trivial magma.
gap> Rank(MagmaByMultiplicationTable([[1]]));
1

gap> STOP_TEST("property_rank.tst");
