---
name: CI
run-name: CI-${{ github.event.number }} ${{ github.event.pull_request.title }}

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

permissions: {}

# the `concurrency` settings ensure that not too many CI jobs run in parallel
concurrency:
  # group by workflow and ref; the last slightly strange component ensures that for pull
  # requests, we limit to 1 concurrent job, but for the master branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  gaptest:
    name: Code quality - unit-tests (${{ matrix.gap-version }})
    runs-on: ubuntu-slim
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        gap-version:
          - 'devel'   # current GAP development version from git
          - 'latest'  # latest GAP release
          - 'minimal' # oldest GAP release supported by this package

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup gap-system
        uses: gap-actions/setup-gap@f12222f1b86ce1f8a246c4000abfd6e69893411c # v3
        with:
          gap-version: ${{ matrix.gap-version }}

      - name: Install additional packages
        shell: bash
        run: |
          gap -c 'LoadPackage("PackageManager"); InstallPackage("digraphs"); QUIT;'

      - name: Build gap-package
        uses: gap-actions/build-pkg@a5d43878fc0af9eec0ec4dff928fc1f7e4e67501 # v3

      - name: Provision documentation for package
        uses: gap-actions/build-pkg-docs@f1927364d4a2df557251a26afca0377edf1163ce # v2
        with:
          use-latex: 'true'

      - name: Run gap-tests
        uses: gap-actions/run-pkg-tests@b1f75421e9d57ebf51a41dfcfa19b9fe2f3030da # v4

      - name: Run gap-tests (only-needed)
        uses: gap-actions/run-pkg-tests@b1f75421e9d57ebf51a41dfcfa19b9fe2f3030da # v4
        with:
          mode: onlyneeded

      - name: Show code-coverage
        uses: gap-actions/process-coverage@500e7ca58e508de2b0dce5d1738f5fd0980bed0a # v3

      - uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  gaplint:
    name: Code quality - gaplint
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.13
          cache: pip

      - name: Install python-dependencies
        uses: py-actions/py-dependency-install@30aa0023464ed4b5b116bd9fbdab87acf01a484e # v4
        with:
          update-pip: true

      - name: Run gaplint
        run: |
          echo "::group:: gaplint -- *.g"
          find . -name '*.g' | xargs -n1 gaplint
          echo "::group:: gaplint -- *.gi"
          find . -name '*.gi' | xargs -n1 gaplint
          echo "::group:: gaplint -- *.gd"
          find . -name '*.gd' | xargs -n1 gaplint
          echo "::group:: gaplint -- *.tst"
          find . -name '*.tst' | xargs -n1 gaplint
