---
name: Label management
run-name: label-management ${{ github.event.number }} ${{ github.event.pull_request.title }}

on:
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  statuses: read
  contents: read
  issues: write
  pull-requests: write

jobs:
  label-auto:
    name: Labels - auto-create
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/config.pull-request-label.yaml

  label-test:
    name: Labels - test
    needs: label-auto
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: maximum
          count: 1
          labels: |
            release-patch
            release-minor
            release-major
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: |
            bug
            feature
            dependencies
            documentation
