---
name: gap-docs
run-name: gap-docs-${{ github.event.number }} ${{ github.event.pull_request.title }}

on:
  pull_request:
    branches:
      - main

# the `concurrency` settings ensure that not too many CI jobs run in parallel
concurrency:
  # group by workflow and ref; the last slightly strange component ensures that for pull
  # requests, we limit to 1 concurrent job, but for the master branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  manual:
    name: gap-build-manual
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: gap-actions/setup-gap@v2
      - uses: gap-actions/build-pkg-docs@v1
        with:
          use-latex: 'true'
      - uses: gap-actions/run-pkg-tests@v2
      - uses: gap-actions/run-pkg-tests@v2
        with:
          only-needed: true
