---
name: Pull-request - pull-request has a linked issue
run-name: pull-request-issue-linked ${{ github.event.number }} ${{ github.event.pull_request.title }}

on:
  pull_request:
    types: [edited, synchronize, opened, reopened]
  check_run:
    types: [created, rerequested, completed, requested_action]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: test
        uses: hattan/verify-linked-issue-action@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
