---
name: Pull-request - user auto-assign
run-name: pull-request user auto-assign ${{ github.event.number }} ${{ github.event.pull_request.title }}

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: read

jobs:
  add-assignment:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: .github/workflows-configs/pull-request-project-assign.yaml

