---
name: Code quality - gaplint
run-name: gaplint-${{ github.event.number }} ${{ github.event.pull_request.title }}

on:
  pull_request:
    branches: 
      - main

jobs:
  gaplint:
    name: Code quality - gaplint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip

      - name: Install python-dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          update-pip: true

      - name: Run gaplint
        run: |
          echo "::group:: gaplint -- *.g"
          find . -name '*.g' | xargs -n1 gaplint
          echo "::group:: gaplint -- *.gi"
          find . -name '*.gi' | xargs -n1 gaplint
          echo "::group:: gaplint -- *.gd"
          find . -name '*.gd' | xargs -n1 gaplint
          echo "::group:: gaplint -- *.tst"
          find . -name '*.tst' | xargs -n1 gaplint
