---
name: Pull-request - user auto-assign
run-name: pull-request user auto-assign ${{ github.event.number }} ${{ github.event.pull_request.title }}

on:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  add-assignment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.github_token }}
          assignees: ${{ github.actor }}
