---
name: pull-request labels-test
run-name: pull-request labels-test ${{ github.event.number }} ${{ github.event.pull_request.title }}

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: maximum
          count: 1
          labels: |
            release-patch
            release-minor
            release-major
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: |
            bug
            feature
            documentation
