# This workflow is responsible for making releases of this GAP package,
# and updating its website afterwards. For usage instructions, see
# <https://github.com/gap-actions/release-pkg/>.
name: Release

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Dry run: only create an archive containing the release instead of publishing it on GitHub"
        type: boolean
        required: false
        default: false
      force:
        description: "Force: allow overwriting an existing release, or making a release with an incorrect date"
        type: boolean
        required: false
        default: false

permissions: write-all

jobs:
  release:
    name: "Release the GAP package"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: gap-actions/setup-gap@56db7f90d3f9cd5dbe13f86ea29bb1c8424521e5 # v3
        with:
          gap-version: 'devel'
      - uses: gap-actions/build-pkg-docs@ee3f0345faaa15e9c0173f8f2aec61e65483168f # v2
        with:
          use-latex: true
      - uses: gap-actions/release-pkg@2f8d281794aa318157238eba8b50ba3711e95872 # v1
        with:
          dry-run: ${{ inputs.dry-run }}
          force: ${{ inputs.force }}
      - uses: gap-actions/update-gh-pages@d503b1c7a412223a9a3564561ed62a5623110d7a # v1
        if: ${{ !inputs.dry-run }}
