---

name: release-gh-page-update
run-name: release-gh-page-update-${{ github.ref_name }}
on:
  workflow_dispatch: 
  release:
    types:
      - published

env:
  gap-branch: stable-4.13

jobs:
  gh-page-update:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: git -- checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: git -- checkout page
        uses: actions/checkout@v4
        with:
          path: gh-pages
          ref: gh-pages

      - uses: gap-actions/setup-gap@v2
        with:
          GAPBRANCH: ${{ env.gap-branch }}

      - name: gap -- build docs
        uses: gap-actions/build-pkg-docs@v1
        with:
          use-latex: 'true'

      - name: metadata -- copy metada to update page
        run: |
          rm -r ./gh-pages/doc
          cp -r ./doc/ ./gh-pages/doc/
          cp ./PackageInfo.g ./gh-pages/PackageInfo.g
          cp ./README.md ./gh-pages/README.md
          rm -v ./gh-pages/doc/.gitignore

      - name: gap -- run update.g
        working-directory: ./gh-pages
        run: |
          gap update.g

      - name: git -- commit the update
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[${{ github.ref_name }}] - website update'
          repository: gh-pages
          branch: gh-pages
          push_options: '--force'