---

name: release
run-name: release-${{ github.ref_name }}
on:
  workflow_dispatch: 
  release:
    types:
      - published

env:
  gap-branch: stable-4.13

jobs:
  gh-page-update:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: git -- checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - uses: gap-actions/setup-gap@v2
        with:
          GAPBRANCH: ${{ env.gap-branch }}

      - name: gap -- build docs
        uses: gap-actions/build-pkg-docs@v1
        with:
          use-latex: 'true'
      
      - name: github -- run clean up for tarball
        run: |
          echo "::group:: cleanup version control metadata"
          rm -rvf .git
          rm -rvf .svn

          echo "::group:: cleanup deployment metadata"
          rm -rvf .github
          rm -v .codecov.yaml
          rm -v .gaplint.yml
          rm -v requirements.txt

          echo "::group:: cleanup macos metadata"
          find . -name .DS_Store -exec rm -f {} +
          
          echo "::group:: remove tex aux files"
          find doc \( -name '*.aux' -o -name '*.bbl' -o -name '*.blg' -o -name '*.brf' -o -name '*.idx' -o -name '*.ilg' -o -name '*.ind' -o -name '*.log' -o -name '*.out' -o -name '*.pnr' -o -name '*.toc' -o -name '*.tst' \) -exec rm -f {} +

      - name: pkg -- build an archive
        run: |
          tar -czvf ${{ github.repository }}-${{ github.ref_name }}.tar.gz .

      - name: github -- upload manual-pdf
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.repository }}-${{ github.ref_name }}.tar.gz
            doc/manual.pdf

